version: '2'
services:
  app:
#    build:
#      context: ./src
    image: doomatel/django-polls-webapp
    depends_on:
      - database
      - redis
    entrypoint: /docker-entrypoint-api.sh
    env_file:
      - ./env.public
      - ./env.private
    environment:
      - REDIS_CONNECTION_STRING=redis://redis/1
    volumes:
#      - ./src:/polls
      - public_files:/polls/public
  celery:
#    build:
#      context: ./src
    image: doomatel/django-polls-webapp
    depends_on:
      - app
      - database
      - redis
    entrypoint: /docker-entrypoint-celery.sh
    env_file:
      - ./env.public
      - ./env.private
    environment:
      - REDIS_CONNECTION_STRING=redis://redis/{redis_db}
    volumes_from:
      - app
  database:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=polls_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
  webserver:
    image: nginx:mainline-alpine
    environment:
      - NGINX_LISTEN=80
    ports:
      - "80:80"
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/app.template
    command: /bin/sh -c "envsubst '$$NGINX_LISTEN'< /etc/nginx/conf.d/app.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  pg_data:
  redis_data:
  public_files:
